service: serverless-line-chatbot

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-1
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  #environment:
  #  SAMPLE_ENV_VAR: ${env:SAMPLE_ENV_VAR}

functions:
  ####
  findjobs:
    handler: handlers/jobfinding.findjobsbot
    events:
      - http:
          path: findjobs
          method: post
  ####
  findjobsweb:
    handler: handlers/jobfinding.findjobsweb
    events:
      - http:
          path: jobs/search
          method: get
  ####
  getvillageprofile:
    handler: handlers/village.getVillageProfile
    events:
      - http:
          path: villages/profile/{idv}
          method: get
  ####
  updatevillageprofile:
    handler: handlers/villagesuperuser.updateVillageProfile
    events:
      - http:
          path: villages/profile/{idv}
          method: patch
  ####
  createvillagejob:
    handler: handlers/villagejob.createVillageJob
    events:
      - http:
          path: village-jobs
          method: post
  listvillagejob:
    handler: handlers/villagejob.listVillageProfile
    events:
      - http:
          path: village-jobs/{idv}
          method: get
  getvillagejob:
    handler: handlers/villagejob.getVillageProfile
    events:
      - http:
          path: village-jobs/{idv}/{idj}
          method: get
  updatevillagejobdetail:
    handler: handlers/villagejob.updateVillageJobDetail
    events:
      - http:
          path: village-job-detail/{idv}/{idj}
          method: patch
  updatevillagejobdetail:
    handler: handlers/villagejob.updateVillageJobStatus
    events:
      - http:
          path: village-job-status/{idv}/{idj}
          method: patch
  completevillagejob:
    handler: handlers/villagejob.completeVillageJob
    events:
      - http:
          path: village-job-complete/{idv}/{idj}
          method: post
  ####
  createvillageadmin:
    handler: handlers/villageuser.createVillageAdmin
    events:
      - http:
          path: village-admins
          method: post
  listvillageadmin:
    handler: handlers/villageuser.listVillageAdmin
    events:
      - http:
          path: village-admins/{idv}
          method: get
  getvillageadmin:
    handler: handlers/villageuser.getVillageAdmin
    events:
      - http:
          path: village-admins/{idv}/{idu}
          method: get
  updatevillageadmin:
    handler: handlers/villageuser.updateVillageAdmin
    events:
      - http:
          path: village-admins/update/{idv}/{idu}
          method: patch
  revokevillageadmin:
    handler: handlers/villageuser.revokeVillageAdmin
    events:
      - http:
          path: village-admins/revoke/{idv}/{idu}
          method: patch
  ####
  createvillageuser:
    handler: handlers/villageuser.createVillageUser
    events:
      - http:
          path: village-users
          method: post
  listvillageuser:
    handler: handlers/villageuser.listVillageUser
    events:
      - http:
          path: village-users/{idv}
          method: get
  getvillageuser:
    handler: handlers/villageuser.getVillageUser
    events:
      - http:
          path: village-users/{idv}/{idu}
          method: get
  updatevillageuser:
    handler: handlers/villageuser.updateVillageUser
    events:
      - http:
          path: village-users/{idv}/{idu}
          method: patch
  deletevillageuser:
    handler: handlers/villageuser.deleteVillageUser
    events:
      - http:
          path: village-users/{idv}/{idu}
          method: delete

# Create our resources with separate CloudFormation templates
resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}